### ISSUE TITLE
DBUser using DBCluster causes the controller to crash

### ISSUE THREAD

**Issue by rbranche** [adobe/proteus-aws-operator#5]
`DBUser` using `DBCluster` causes the controller to crash.

```
apiVersion: v1
data:
    password: ZGVhZGJlYWZkZWFkYmVhZmRlYWRiZWFm
kind: Secret
metadata:
    name: branche-test-rds-master-password
---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
    name: branche-test
spec:
    databaseName: database_name
    dbClusterIdentifier: us-east-1-branche-test
    dbSubnetGroupName: branche-test
    engine: aurora-mysql
    masterUserPassword:
        key: password
        name: branche-test-rds-master-password
        namespace: preview
    masterUsername: root
---
apiVersion: rds.services.k8s.aws.adobe.io/v1alpha1
kind: DBUser
metadata:
    name: branche-test-admin
spec:
    dbClusterIdentifier: -branche-test
    grantStatement: GRANT ALL ON `%`.* TO ? REQUIRE SSL
    useIAMAuthentication: true
    username: admin
```
